#!/bin/sh

# ------------------------------------------------------------------------------
# Dotfiles
# ------------------------------------------------------------------------------
alias dots='git --git-dir="${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles/dots" --work-tree="$HOME"'
alias lazydots='lazygit --git-dir="${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles/dots" --work-tree="$HOME"'

alias privs='git --git-dir="${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles/private" --work-tree="$HOME"'
alias lazyprivs='lazygit --git-dir="${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles/private" --work-tree="$HOME"'

__git_complete dots __git_main 2>/dev/null
__git_complete privs __git_main 2>/dev/null

# ------------------------------------------------------------------------------
# Use neovim > vim > vi
# ------------------------------------------------------------------------------
command -v nvim >/dev/null && alias vim='nvim' vimdiff='nvim -d' sudovimdiff='SUDO_EDITOR="nvim -d" sudoedit'
command -v vim >/dev/null && alias vi='vim'

# ------------------------------------------------------------------------------
# Package stuff
# ------------------------------------------------------------------------------
alias pactable='expac -Q -H M --timefmt="%Y-%m-%d %T" "%l  %-12w  %-15m  %n (%v)"'
alias pacdate='(echo -e "$(uptime -s)  BOOT" ; pactable) | sort -n | grep "^\|.*BOOT$"'
alias pacsize='pactable | sort -hk 4'
alias pacdep='expac -Q "%-25n\t%D"'
alias pacclean='pacman -Qtdq > /dev/null && sudo pacman -Rnsu $(pacman -Qtdq)'
alias updmirror='reflector -a 48 -c no,se,dk,fi,de,nl,be,fr,pl,at,gb -p https --sort country | sudo tee /etc/pacman.d/mirrorlist'

# ------------------------------------------------------------------------------
# Add colors
# ------------------------------------------------------------------------------
alias ls='ls -hN --color=auto --group-directories-first'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'

# ------------------------------------------------------------------------------
# Stuff
# ------------------------------------------------------------------------------
alias cp='cp -i'
alias df='df -h'
alias du='du -h'
alias e='$EDITOR'
alias v='$VISUAL'
alias notes='zk edit --interactive --sort modified'
alias wcurl='curl -OJLR'
alias nettfart='speedtest -s 12919'
alias xod='od --endian=big -t x2z'
alias newsboat='newsboat -q'
command -v xdg-open >/dev/null && alias open='xdg-open'

# ------------------------------------------------------------------------------
# Directories and config shortcuts
# ------------------------------------------------------------------------------
cdf() {
    b="$(bookmarks dir "$1")"
    [ -d "$b" ] && cd "$b"
}
cff() {
    b="$(bookmarks file "$1")"
    [ -f "$b" ] && sensible-editor "$b"
}
