#!/usr/bin/env bash
# shellcheck disable=SC2034

# ------------------------------------------------------------------------------
# Set colorful PS1
# ------------------------------------------------------------------------------
__ps1() {
    # colors, prompting
    if [ -z "${ZSH_VERSION}" ]; then
        # bash
        local cr='\[\e[31m\]' cg='\[\e[32m\]' cy='\[\e[33m\]'
        local cb='\[\e[34m\]' cm='\[\e[35m\]' cc='\[\e[36m\]'
        local cw='\[\e[37m\]' reset='\[\e[0m\]' bold='\[\e[1m\]'
        local u='\u' h='\h' w='\w' W='\W' p='\$'
    else
        # zsh
        local cr='%F{red}' cg='%F{green}' cy='%F{yellow}'
        local cb='%F{blue}' cm='%F{magenta}' cc='%F{cyan}'
        local cw='%F{white}' reset='%f%b' bold='%B'
        local u='%n' h='%m' w='%~' W='%1~' p='%#'
    fi

    local c="$cb"   # main color: blue
    local cu="$cg"  # user color: green
    local ch="$cg"  # host color: green

    # different user color (root) and host color (remote/ssh)
    [ $EUID -eq 0 ] && cu="$cr" # user color: red
    [ -n "${SSH_CLIENT}${SSH_TTY}${SSH_CONNECTION}" ] && ch="$cy" # host color: yellow

    # git
    local git="\$(git branch --show-current 2>/dev/null | sed 's/\(.*\)/ (\1)/')"

    # PS1
    echo "$bold$c┌[$cu$u$c@$ch$h $cc$w$cm$git$c]"
    echo "$bold$c└─$cu$p $reset"
    # echo "$bold${c}[$cu$u$c@$ch$h $cc$W$c]$cu$p$c $reset"
}

PS1="$(__ps1)"
