#!/usr/bin/env bash

# Here awesome is kept as default
[ "$1" ] || set -- "awesome"
case $1 in
  awesome)  set -- "awesome"
        DESKTOP_SESSION="awesome" ;;
  i3|i3wm)  set -- "i3"
        DESKTOP_SESSION="i3" ;;
  dwm)      set -- "dwm"
        DESKTOP_SESSION="dwm" ;;
  openbox)  set -- "openbox-session"
        DESKTOP_SESSION="openbox" ;;
  xfce|xfce4)   set -- "startxfce4"
        DESKTOP_SESSION="xfce" ;;
  gnome3)   set -- "gnome-session"
        DESKTOP_SESSION="gnome" ;;
  lxqt)     set -- "lxqt-session"
        DESKTOP_SESSION="lxqt" ;;
  lxde)     set -- "startlxde"
        DESKTOP_SESSION="lxde" ;;
  kde)      set -- "startkde"
        DESKTOP_SESSION="kde-plasma" ;;
esac
export DESKTOP_SESSION

# Import .xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Execute DE/WM
exec "$@"
