#!/usr/bin/env bash

# QT Stuff
export QT_QPA_PLATFORMTHEME="gtk2"
export QT_AUTO_SCREEN_SCALE_FACTOR=0

# JRE stuff
JDK_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
JDK_JAVA_OPTIONS+=' -Dswing.aatext=true'
JDK_JAVA_OPTIONS+=' -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
export JDK_JAVA_OPTIONS

# Load Xresources
xrdb -merge "${XDG_CONFIG_HOME:-$HOME/.config}/desktop/Xresources" 2>/dev/null

# Autorun
. ${XDG_CONFIG_HOME:-$HOME/.config}/desktop/autorun
