#!/usr/bin/env bash

file="${XDG_DATA_HOME:-$HOME/.local/share}/emoji.txt"
url="https://unicode.org/Public/emoji/15.1/emoji-test.txt"

# Download and parse emoji-test.txt from unicode.org if it doesn't exist
dl="yes"
while [ ! -s "$file" ]; do
    if [ "$dl" = "yes" ]; then
        curl -sSf "$url" 2>/dev/null | \
            sed '{
                /^\(#\|\s*$\)/d
                s/.*#\s*\([^[:space:]]\+\)\s\+[^[:space:]]\+\s\+\(.*\)/\1\t\2/
            }' > "$file"
        unset dl
    else
        notify-send "rofi-emoji" "Error downloading emoji file from unicode.org"
        exit 1
    fi
done

case "$ROFI_RETV" in
    0) # Initial call of script
        echo -en "\x00prompt\x1fSelect emoji\n"
        cat "$file"
        ;;
    1) # Selected an entry
        chosen="${1%%[[:space:]]*}"
        [ -z "$chosen" ] && exit 0
        coproc {
            printf "%s" "$chosen" | xclip -selection clipboard 2>/dev/null
            printf "%s" "$chosen" | wl-copy 2>/dev/null
            notify-send "rofi-emoji" "'$chosen' copied to clipboard."
        } >/dev/null 2>&1
        ;;
esac
